version: '3.2'
services:
  borrow:
    image: oasisdexorg/oasis-borrow:latest
    container_name: oasis-borrow
    depends_on:
      - postgres
      - localnode
    command:
      ['./scripts/wait-for-it.sh', 'postgres-oasis-borrow:5432', '--', 'npm', 'run', 'start:prod']
    environment:
      - CHALLENGE_JWT_SECRET=${CHALLENGE_JWT_SECRET}
      - USER_JWT_SECRET=${USER_JWT_SECRET}
      - MIXPANEL_ENV=${MIXPANEL_ENV}
      - MIXPANEL_KEY=${MIXPANEL_KEY}
      - ADROLL_ADV_ID=${ADROLL_ADV_ID}
      - ADROLL_PIX_ID=${ADROLL_PIX_ID}
      - MAINNET_CACHE_URL=${MAINNET_CACHE_URL}
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - INFURA_PROJECT_ID_BACKEND=${INFURA_PROJECT_ID_BACKEND}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - USE_TERMS_OF_SERVICE=${USE_TERMS_OF_SERVICE}
      - MULTIPLY_PROXY_ACTIONS=${MULTIPLY_PROXY_ACTIONS}
      - EXCHANGE=${EXCHANGE}
      - DUMMY_EXCHANGE=${DUMMY_EXCHANGE}
      - USE_DUMMY=${USE_DUMMY}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:3000'
