services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER}'" ]
      interval: 3s
      timeout: 30s
      retries: 10
  pgadmin:
    image: dcagatay/pwless-pgadmin4:7.6
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:80/misc/ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: False
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: False
    volumes:
      - pgadmin-data:/var/lib/pgadminvolumes

volumes:
  db_data:
    driver: local
  pgadmin-data:
    driver: local
